import streamlit as st

st.title("Test Quiz")
st.write("Choose a topic to test your knowledge!")

# Define quiz topics and questions
quiz_data = {
    "Python": [
    {"question": "What is the output of `print(2**3)`?", "options": ["6", "8", "9", "10"], "answer": "8"},
    {"question": "Which keyword is used to define a function in Python?", "options": ["func", "def", "function", "lambda"], "answer": "def"},
    {"question": "Which of these is used for comments in Python?", "options": ["//", "#", "/* */", "'"], "answer": "#"},
    {"question": "Which data type is immutable in Python?", "options": ["list", "set", "dictionary", "tuple"], "answer": "tuple"},
    {"question": "What does `len()` do in Python?", "options": ["Returns size of an object", "Counts unique elements", "Calculates memory usage", "Checks data type"], "answer": "Returns size of an object"},
    {"question": "How do you create a virtual environment in Python?", "options": ["venv create", "python -m venv", "pyenv create", "virtualenv start"], "answer": "python -m venv"},
    {"question": "What is the output of `print(type([]))`?", "options": ["<class 'list'>", "<class 'tuple'>", "<class 'array'>", "<class 'set'>"], "answer": "<class 'list'>"},
    {"question": "What is the correct file extension for Python files?", "options": [".py", ".pt", ".python", ".p"], "answer": ".py"},
    {"question": "What is the keyword to create a class in Python?", "options": ["class", "Class", "cls", "create"], "answer": "class"},
    {"question": "What is the result of `10//3`?", "options": ["3", "3.33", "3.0", "None"], "answer": "3"},
    {"question": "How do you install a Python package?", "options": ["pip install", "pkg install", "python -install", "pip add"], "answer": "pip install"},
    {"question": "Which of these is not a Python data type?", "options": ["set", "list", "array", "stack"], "answer": "stack"},
    {"question": "What is the correct way to handle exceptions in Python?", "options": ["try-catch", "try-except", "try-finally", "try-handler"], "answer": "try-except"},
    {"question": "What is the default value of the `end` parameter in the `print()` function?", "options": ["\\n", "space", "\\t", "None"], "answer": "\\n"},
    {"question": "What is a Python dictionary?", "options": ["A list of keys", "Key-value pairs", "An ordered list", "A sequence"], "answer": "Key-value pairs"},
    {"question": "What does `is` check in Python?", "options": ["Value equality", "Object identity", "Data type", "None"], "answer": "Object identity"},
    {"question": "What is the output of `bool('False')`?", "options": ["True", "False", "None", "Error"], "answer": "True"},
    {"question": "Which Python function is used to convert a string to an integer?", "options": ["str()", "int()", "convert()", "to_int()"], "answer": "int()"},
    {"question": "How is a block of code defined in Python?", "options": ["Indentation", "Brackets", "Parentheses", "Curly braces"], "answer": "Indentation"},
    {"question": "What is the output of `print(5 > 3 > 1)`?", "options": ["True", "False", "Error", "None"], "answer": "True"},
    {"question": "Which of these is not a valid Python loop?", "options": ["for", "while", "do-while", "repeat-until"], "answer": "repeat-until"},
    {"question": "What is the output of `print(3 * 'Hello')`?", "options": ["HelloHelloHello", "Error", "3Hello", "Hello*3"], "answer": "HelloHelloHello"},
    {"question": "How do you declare a variable in Python?", "options": ["var x = 5", "int x = 5", "x = 5", "declare x = 5"], "answer": "x = 5"},
    {"question": "What does `a += 1` mean in Python?", "options": ["a = a + 1", "Increment a by 1", "Update value of a", "All of the above"], "answer": "All of the above"},
    {"question": "Which of these is not a Python keyword?", "options": ["class", "yield", "public", "lambda"], "answer": "public"},
    {"question": "Which operator is used for exponentiation?", "options": ["^", "**", "exp", "pow"], "answer": "**"},
    {"question": "How do you get the last element of a list in Python?", "options": ["list[len(list)]", "list[-1]", "list[last]", "list.end"], "answer": "list[-1]"},
    {"question": "Which module is used to handle JSON in Python?", "options": ["os", "json", "re", "sys"], "answer": "json"},
    {"question": "Which method is used to remove an element from a set?", "options": ["del()", "remove()", "pop()", "discard()"], "answer": "remove()"},
    {"question": "What is the output of `print('5' + '5')`?", "options": ["55", "10", "Error", "None"], "answer": "55"},
    {"question": "What is the output of `len('Python')`?", "options": ["6", "5", "7", "Error"], "answer": "6"},
    {"question": "How do you write an empty function in Python?", "options": ["pass", "None", "return", "empty"], "answer": "pass"},
    {"question": "What does the `range()` function return?", "options": ["List", "Tuple", "Sequence", "Set"], "answer": "Sequence"},
    {"question": "Which Python function is used to read input from the user?", "options": ["input()", "read()", "prompt()", "scan()"], "answer": "input()"},
    {"question": "Which statement is used to stop a loop in Python?", "options": ["break", "stop", "exit", "quit"], "answer": "break"},
    {"question": "What does `list.append()` do?", "options": ["Adds an element at the end", "Adds an element at the start", "Replaces last element", "Creates a new list"], "answer": "Adds an element at the end"},
    {"question": "Which method removes whitespace from the start and end of a string?", "options": ["trim()", "strip()", "clear()", "remove()"], "answer": "strip()"},
    {"question": "Which function is used to check the type of an object in Python?", "options": ["check()", "type()", "class()", "isinstance()"], "answer": "type()"},
    {"question": "Which library is used for data manipulation in Python?", "options": ["Pandas", "NumPy", "Matplotlib", "SciPy"], "answer": "Pandas"},
    {"question": "What does `*args` allow in function definitions?", "options": ["Multiple arguments", "Optional arguments", "Keyword arguments", "None"], "answer": "Multiple arguments"},
    {"question": "What is the output of `5 % 2`?", "options": ["1", "2", "0", "5"], "answer": "1"},
    {"question": "Which keyword is used to inherit a class?", "options": ["extend", "inherit", "super", "class"], "answer": "super"},
    {"question": "How do you create a list comprehension in Python?", "options": ["[x for x in range(5)]", "(x for x in range(5))", "list[x in range(5)]", "All are valid"], "answer": "[x for x in range(5)]"},
    {"question": "Which of these is mutable?", "options": ["list", "tuple", "str", "int"], "answer": "list"},
    {"question": "What is the output of `print(True + False)`?", "options": ["1", "0", "Error", "True"], "answer": "1"},
    {"question": "Which function converts a list to a set?", "options": ["convert()", "set()", "list()", "None"], "answer": "set()"},
    {"question": "Which method converts a string to lowercase?", "options": ["toLower()", "lowercase()", "lower()", "strtolower()"], "answer": "lower()"},
    {"question": "What is the output of `[1, 2] + [3, 4]`?", "options": ["[1, 2, 3, 4]", "[1, 2, [3, 4]]", "Error", "None"], "answer": "[1, 2, 3, 4]"},
    {"question": "How do you handle multiple exceptions in Python?", "options": ["try: except (Error1, Error2):", "try: catch Error1 or Error2:", "try: except Error1 or Error2:", "None of these"], "answer": "try: except (Error1, Error2):"},
    {"question": "Which method is used to join elements of a list into a single string?", "options": ["concat()", "join()", "merge()", "combine()"], "answer": "join()"},
],
    "Java": [
    {"question": "What is the size of an int in Java?", "options": ["16 bits", "32 bits", "64 bits", "8 bits"], "answer": "32 bits"},
    {"question": "Which keyword is used to create a class in Java?", "options": ["class", "Class", "define", "struct"], "answer": "class"},
    {"question": "Which method is the entry point of a Java program?", "options": ["main()", "start()", "run()", "entry()"], "answer": "main()"},
    {"question": "Which of these is not a Java primitive data type?", "options": ["int", "float", "boolean", "String"], "answer": "String"},
    {"question": "What is the default value of a boolean in Java?", "options": ["true", "false", "0", "null"], "answer": "false"},
    {"question": "Which operator is used to compare two values?", "options": ["==", "=", "equals", "compare"], "answer": "=="},
    {"question": "Which of these is not an access specifier in Java?", "options": ["public", "private", "protected", "internal"], "answer": "internal"},
    {"question": "Which package is imported by default in every Java program?", "options": ["java.util", "java.lang", "java.io", "java.net"], "answer": "java.lang"},
    {"question": "What is the result of 5 + 2 * 3 in Java?", "options": ["21", "11", "15", "Error"], "answer": "11"},
    {"question": "How do you create an object in Java?", "options": ["ClassName obj = new ClassName();", "new ClassName obj();", "create ClassName obj();", "Object obj = ClassName();"], "answer": "ClassName obj = new ClassName();"},
    {"question": "What is the default value of a reference variable?", "options": ["null", "0", "undefined", "empty"], "answer": "null"},
    {"question": "Which method is used to find the length of a string in Java?", "options": ["size()", "length()", "getSize()", "getLength()"], "answer": "length()"},
    {"question": "What is an interface in Java?", "options": ["A class with abstract methods", "A collection of methods", "A blueprint of a class", "None of the above"], "answer": "A blueprint of a class"},
    {"question": "Which keyword is used to inherit a class?", "options": ["extends", "inherits", "super", "implements"], "answer": "extends"},
    {"question": "Which exception is thrown when dividing by zero?", "options": ["ArithmeticException", "NullPointerException", "DivideByZeroException", "IllegalArgumentException"], "answer": "ArithmeticException"},
    {"question": "Which of these is a checked exception?", "options": ["IOException", "ArithmeticException", "NullPointerException", "ArrayIndexOutOfBoundsException"], "answer": "IOException"},
    {"question": "Which method is used to start a thread in Java?", "options": ["run()", "execute()", "start()", "init()"], "answer": "start()"},
    {"question": "What is the use of the `this` keyword?", "options": ["To refer to the current object", "To call parent methods", "To create objects", "To terminate the program"], "answer": "To refer to the current object"},
    {"question": "What does JVM stand for?", "options": ["Java Virtual Machine", "Java Visual Machine", "Java Verification Machine", "Java Version Manager"], "answer": "Java Virtual Machine"},
    {"question": "Which of these is not a valid Java loop?", "options": ["for", "while", "do-while", "foreach"], "answer": "foreach"},
    {"question": "What is the use of the `final` keyword?", "options": ["To prevent inheritance", "To create constants", "Both A and B", "None of the above"], "answer": "Both A and B"},
    {"question": "Which collection does not allow duplicate elements?", "options": ["List", "Set", "Map", "Array"], "answer": "Set"},
    {"question": "Which method is used to terminate a thread in Java?", "options": ["stop()", "terminate()", "destroy()", "exit()"], "answer": "stop()"},
    {"question": "How do you declare a constant in Java?", "options": ["const int x = 5;", "final int x = 5;", "constant int x = 5;", "int x = const 5;"], "answer": "final int x = 5;"},
    {"question": "Which keyword is used to handle exceptions in Java?", "options": ["try", "catch", "throw", "All of the above"], "answer": "All of the above"},
    {"question": "Which of these is not part of Java's OOP principles?", "options": ["Inheritance", "Encapsulation", "Polymorphism", "Pointers"], "answer": "Pointers"},
    {"question": "Which loop is guaranteed to execute at least once?", "options": ["for", "while", "do-while", "foreach"], "answer": "do-while"},
    {"question": "What is the default value of a float in Java?", "options": ["0.0f", "0", "null", "NaN"], "answer": "0.0f"},
    {"question": "What is the purpose of the `super` keyword?", "options": ["To call parent class methods", "To access parent class constructors", "Both A and B", "None"], "answer": "Both A and B"},
    {"question": "Which of these is a Java wrapper class?", "options": ["Integer", "int", "long", "float"], "answer": "Integer"},
    {"question": "Which of these is not a valid Java keyword?", "options": ["static", "abstract", "volatile", "mutable"], "answer": "mutable"},
    {"question": "What is the result of 5 << 1 in Java?", "options": ["10", "15", "20", "Error"], "answer": "10"},
    {"question": "Which class is used to handle file I/O in Java?", "options": ["File", "InputStream", "BufferedReader", "All of the above"], "answer": "All of the above"},
    {"question": "What is the use of the `volatile` keyword?", "options": ["To make a variable thread-safe", "To declare constants", "To prevent inheritance", "None"], "answer": "To make a variable thread-safe"},
    {"question": "Which method is used to compare strings in Java?", "options": ["equals()", "compare()", "compareTo()", "Both A and C"], "answer": "Both A and C"},
    {"question": "What does the `static` keyword mean in Java?", "options": ["Shared across all objects", "Unmodifiable", "Temporary", "Final"], "answer": "Shared across all objects"},
    {"question": "Which exception is thrown when accessing an invalid array index?", "options": ["IndexOutOfBoundsException", "ArrayIndexOutOfBoundsException", "IllegalAccessException", "NullPointerException"], "answer": "ArrayIndexOutOfBoundsException"},
    {"question": "What is the result of 10 % 3 in Java?", "options": ["1", "0", "10", "Error"], "answer": "1"},
    {"question": "What does the `abstract` keyword mean?", "options": ["Defines a method without implementation", "Defines a constant", "Defines a thread", "None"], "answer": "Defines a method without implementation"},
    {"question": "Which method is used to get the current system time?", "options": ["System.currentTimeMillis()", "Date.now()", "Timer.time()", "None"], "answer": "System.currentTimeMillis()"},
    {"question": "What is the purpose of the `instanceof` keyword?", "options": ["To check object type", "To compare objects", "To clone objects", "None"], "answer": "To check object type"},
    {"question": "Which of these is a reserved keyword?", "options": ["goto", "namespace", "delete", "function"], "answer": "goto"},
    {"question": "What is the default value of a char in Java?", "options": ["\\u0000", "null", "empty", "0"], "answer": "\\u0000"},
    {"question": "How do you terminate a loop in Java?", "options": ["break", "exit", "stop", "terminate"], "answer": "break"},
    {"question": "What is the difference between `==` and `equals()`?", "options": ["`==` checks reference, `equals()` checks value", "`==` is for primitive types", "`equals()` is a method", "None"], "answer": "`==` checks reference, `equals()` checks value"},
    {"question": "Which keyword is used to implement an interface?", "options": ["extend", "implements", "inherit", "super"], "answer": "implements"},
],
    "C++": [
    {"question": "Which operator is used to access the address of a variable?", "options": ["*", "&", "%", "@"], "answer": "&"},
    {"question": "Which of these is not a C++ access specifier?", "options": ["public", "private", "protected", "hidden"], "answer": "hidden"},
    {"question": "What is the size of an int in C++?", "options": ["2 bytes", "4 bytes", "8 bytes", "Depends on the system"], "answer": "Depends on the system"},
    {"question": "Which keyword is used to define a constant in C++?", "options": ["const", "constant", "define", "final"], "answer": "const"},
    {"question": "Which symbol is used for single-line comments in C++?", "options": ["//", "/*", "#", "%%"], "answer": "//"},
    {"question": "What is the purpose of the `new` operator in C++?", "options": ["To allocate memory", "To create objects", "Both A and B", "None"], "answer": "Both A and B"},
    {"question": "Which function is the entry point of a C++ program?", "options": ["start()", "main()", "begin()", "run()"], "answer": "main()"},
    {"question": "Which header file is required for input/output operations in C++?", "options": ["<iostream>", "<stdio.h>", "<fstream>", "<io.h>"], "answer": "<iostream>"},
    {"question": "Which data structure does a stack follow?", "options": ["FIFO", "LIFO", "Random", "Priority-based"], "answer": "LIFO"},
    {"question": "What is a destructor in C++?", "options": ["A function to deallocate memory", "A function to initialize an object", "A function to destroy a program", "None"], "answer": "A function to deallocate memory"},
    {"question": "What is the use of the `this` pointer?", "options": ["To access the current object", "To call parent class methods", "To access static members", "None"], "answer": "To access the current object"},
    {"question": "Which of these is not a valid loop in C++?", "options": ["for", "while", "do-while", "foreach"], "answer": "foreach"},
    {"question": "What is the purpose of the `virtual` keyword?", "options": ["To enable polymorphism", "To define abstract classes", "Both A and B", "None"], "answer": "Both A and B"},
    {"question": "Which keyword is used for exception handling in C++?", "options": ["try", "catch", "throw", "All of the above"], "answer": "All of the above"},
    {"question": "What does STL stand for?", "options": ["Standard Template Library", "System Template Library", "Simple Template Library", "Structured Template Library"], "answer": "Standard Template Library"},
    {"question": "What is the default access specifier for class members in C++?", "options": ["public", "private", "protected", "internal"], "answer": "private"},
    {"question": "Which operator cannot be overloaded in C++?", "options": ["+", "-", "::", "++"], "answer": "::"},
    {"question": "What is the purpose of a copy constructor?", "options": ["To initialize a new object", "To copy data from an existing object", "Both A and B", "None"], "answer": "To copy data from an existing object"},
    {"question": "Which of these is not a valid C++ keyword?", "options": ["auto", "final", "goto", "null"], "answer": "null"},
    {"question": "Which function is used to read a string in C++?", "options": ["cin", "getline", "scanf", "fgets"], "answer": "getline"},
    {"question": "Which loop is guaranteed to execute at least once?", "options": ["for", "while", "do-while", "None"], "answer": "do-while"},
    {"question": "What is the default value of a pointer in C++?", "options": ["null", "0", "undefined", "nullptr"], "answer": "nullptr"},
    {"question": "Which operator is used to allocate memory in C++?", "options": ["alloc", "malloc", "new", "create"], "answer": "new"},
    {"question": "What is function overloading in C++?", "options": ["Using multiple functions with the same name", "Using virtual functions", "Overriding parent methods", "None"], "answer": "Using multiple functions with the same name"},
    {"question": "Which keyword is used to define a template in C++?", "options": ["template", "class", "typename", "Both A and C"], "answer": "Both A and C"},
    {"question": "What does the `delete` operator do?", "options": ["Deallocates memory", "Deletes a variable", "Destroys objects", "None"], "answer": "Deallocates memory"},
    {"question": "Which header file is used for file handling in C++?", "options": ["<file.h>", "<fstream>", "<stdio.h>", "<iostream>"], "answer": "<fstream>"},
    {"question": "Which of these is a reserved keyword?", "options": ["int", "main", "continue", "None"], "answer": "continue"},
    {"question": "What is a pure virtual function?", "options": ["A function with no implementation", "A function declared using `virtual`", "A function declared using `abstract`", "None"], "answer": "A function with no implementation"},
    {"question": "Which function is used to find the length of a string in C++?", "options": ["length()", "size()", "Both A and B", "strlen()"], "answer": "Both A and B"},
    {"question": "Which keyword is used to inherit a class in C++?", "options": ["inherits", "extends", "class", "None"], "answer": "None (Use `:`)"},
    {"question": "What is the result of 5 % 2 in C++?", "options": ["1", "2", "0", "Error"], "answer": "1"},
    {"question": "Which operator is used to access members of a structure?", "options": [".", "->", "::", "None"], "answer": "."},
    {"question": "What does the `inline` keyword mean?", "options": ["Suggests inline expansion", "Creates constants", "Defines virtual methods", "None"], "answer": "Suggests inline expansion"},
    {"question": "Which method is used to terminate a program in C++?", "options": ["exit()", "terminate()", "stop()", "None"], "answer": "exit()"},
    {"question": "Which of these is a valid C++ constant?", "options": ["const int x;", "define x;", "constexpr x;", "All"], "answer": "const int x;"},
    {"question": "What is the use of `static` in C++?", "options": ["To define shared variables", "To prevent reinitialization", "Both A and B", "None"], "answer": "Both A and B"},
    {"question": "Which header file provides mathematical functions in C++?", "options": ["<cmath>", "<math>", "<math.h>", "<iostream>"], "answer": "<cmath>"},
    {"question": "Which of these is a pointer declaration?", "options": ["int *ptr;", "int ptr;", "int[] ptr;", "None"], "answer": "int *ptr;"},
    {"question": "What is a namespace in C++?", "options": ["A way to group identifiers", "A keyword to create functions", "A template for classes", "None"], "answer": "A way to group identifiers"},
    {"question": "Which operator is used to dereference a pointer?", "options": ["*", "&", "::", "."], "answer": "*"},
    {"question": "Which method is used to find the size of an array?", "options": ["sizeof", "length", "size", "None"], "answer": "sizeof"},
    {"question": "Which of these is not a valid data type in C++?", "options": ["int", "long", "short", "float32"], "answer": "float32"},
    {"question": "What does the `explicit` keyword prevent?", "options": ["Implicit conversions", "Multiple inheritance", "Polymorphism", "None"], "answer": "Implicit conversions"},
    {"question": "Which function is used to get the current system time?", "options": ["time()", "system_time()", "ctime()", "None"], "answer": "time()"},
    {"question": "Which operator is used to get the remainder in division?", "options": ["%", "/", "//", "None"], "answer": "%"},
],
    "Streamlit": [
    {"question": "Which function is used to display text in Streamlit?", "options": ["st.text()", "st.write()", "st.display()", "st.print()"], "answer": "st.write()"},
    {"question": "Which command is used to run a Streamlit app?", "options": ["python app.py", "streamlit run app.py", "streamlit start", "python -m streamlit"], "answer": "streamlit run app.py"},
    {"question": "Which function is used to create a sidebar in Streamlit?", "options": ["st.sidebar()", "st.create_sidebar()", "st.side()", "st.add_sidebar()"], "answer": "st.sidebar()"},
    {"question": "How do you create a button in Streamlit?", "options": ["st.button()", "st.create_button()", "st.add_button()", "st.btn()"], "answer": "st.button()"},
    {"question": "Which function is used to display charts in Streamlit?", "options": ["st.chart()", "st.pyplot()", "st.graph()", "st.plot()"], "answer": "st.pyplot()"},
    {"question": "What is the default port for Streamlit apps?", "options": ["8501", "5000", "8080", "8888"], "answer": "8501"},
    {"question": "Which method is used to add a dropdown menu?", "options": ["st.dropdown()", "st.selectbox()", "st.dropdown_menu()", "st.choice()"], "answer": "st.selectbox()"},
    {"question": "How can you display a DataFrame in Streamlit?", "options": ["st.table()", "st.dataframe()", "Both A and B", "None"], "answer": "Both A and B"},
    {"question": "What is the purpose of `st.cache()`?", "options": ["To cache data for faster loading", "To store files locally", "To cache user inputs", "None"], "answer": "To cache data for faster loading"},
    {"question": "Which function is used to upload files in Streamlit?", "options": ["st.upload()", "st.file_uploader()", "st.add_file()", "st.file_upload()"], "answer": "st.file_uploader()"},
    {"question": "What is the purpose of `st.progress()`?", "options": ["To show a progress bar", "To add animations", "To display messages", "None"], "answer": "To show a progress bar"},
    {"question": "Which function is used to show images in Streamlit?", "options": ["st.image()", "st.show_image()", "st.img()", "st.display_image()"], "answer": "st.image()"},
    {"question": "How can you display markdown in Streamlit?", "options": ["st.markdown()", "st.write()", "Both A and B", "None"], "answer": "Both A and B"},
    {"question": "Which Streamlit component is used for sliders?", "options": ["st.slider()", "st.range()", "st.scrollbar()", "st.move_slider()"], "answer": "st.slider()"},
    {"question": "How do you set a title for your Streamlit app?", "options": ["st.title()", "st.header()", "st.subheader()", "st.app_title()"], "answer": "st.title()"},
    {"question": "Which layout option allows Streamlit apps to expand to full width?", "options": ["wide", "full", "expand", "fullscreen"], "answer": "wide"},
    {"question": "How do you add a checkbox in Streamlit?", "options": ["st.checkbox()", "st.check_box()", "st.toggle()", "st.box()"], "answer": "st.checkbox()"},
    {"question": "What is the primary file format for Streamlit apps?", "options": [".py", ".streamlit", ".html", ".ipynb"], "answer": ".py"},
    {"question": "How do you display code in Streamlit?", "options": ["st.code()", "st.snippet()", "st.text()", "st.show_code()"], "answer": "st.code()"},
    {"question": "Which command reruns the Streamlit app?", "options": ["Ctrl+R", "Ctrl+C", "Ctrl+S", "R"], "answer": "R"},
    {"question": "Which function is used to create a line chart?", "options": ["st.line_chart()", "st.chart()", "st.plot()", "st.create_chart()"], "answer": "st.line_chart()"},
    {"question": "How do you install Streamlit?", "options": ["pip install streamlit", "conda install streamlit", "install streamlit", "pip install stream"], "answer": "pip install streamlit"},
    {"question": "Which widget allows for multi-selection?", "options": ["st.multiselect()", "st.multi_choice()", "st.multi_dropdown()", "st.select_multiple()"], "answer": "st.multiselect()"},
    {"question": "Which Streamlit function is used to write raw HTML?", "options": ["st.markdown()", "st.html()", "st.raw_html()", "None"], "answer": "st.markdown()"},
    {"question": "What does the `st.experimental_rerun()` function do?", "options": ["Reruns the app", "Refreshes a widget", "Clears the cache", "None"], "answer": "Reruns the app"},
    {"question": "How can you display a map in Streamlit?", "options": ["st.map()", "st.display_map()", "st.show_map()", "st.plot_map()"], "answer": "st.map()"},
    {"question": "What does the `st.columns()` function create?", "options": ["A column layout", "A grid", "A sidebar", "None"], "answer": "A column layout"},
    {"question": "What type of chart is created using `st.bar_chart()`?", "options": ["Bar chart", "Line chart", "Pie chart", "Histogram"], "answer": "Bar chart"},
    {"question": "Which method creates a text input field?", "options": ["st.text_input()", "st.input()", "st.text()", "st.input_text()"], "answer": "st.text_input()"},
    {"question": "Which of these is a valid Streamlit component?", "options": ["st.radio()", "st.slider()", "st.selectbox()", "All of the above"], "answer": "All of the above"},
    {"question": "Which file format does Streamlit use for configuration?", "options": [".toml", ".yaml", ".json", ".config"], "answer": ".toml"},
    {"question": "How do you add a multiselect dropdown?", "options": ["st.multiselect()", "st.dropdown()", "st.multi_dropdown()", "st.choice()"], "answer": "st.multiselect()"},
    {"question": "Which Streamlit component is used to create tabs?", "options": ["st.tabs()", "st.pages()", "st.menu()", "st.switch()"], "answer": "st.tabs()"},
    {"question": "Which function is used for range sliders?", "options": ["st.slider()", "st.range_slider()", "st.range()", "st.multi_slider()"], "answer": "st.slider()"},
    {"question": "How do you show a date picker in Streamlit?", "options": ["st.date_input()", "st.date_picker()", "st.calendar()", "st.pick_date()"], "answer": "st.date_input()"},
    {"question": "Which layout option allows a sidebar to collapse?", "options": ["collapsed", "narrow", "collapsed_sidebar", "hidden"], "answer": "collapsed"},
    {"question": "How do you save session state in Streamlit?", "options": ["st.session_state", "st.save_state()", "st.cache()", "st.store_state()"], "answer": "st.session_state"},
    {"question": "What does `st.warning()` do?", "options": ["Displays a warning message", "Displays a progress bar", "Stops the app", "None"], "answer": "Displays a warning message"},
    {"question": "What is the purpose of `st.write()`?", "options": ["Display text or data", "Log messages", "Create files", "All of the above"], "answer": "Display text or data"},
    {"question": "How do you create radio buttons?", "options": ["st.radio()", "st.choice()", "st.select_one()", "st.options()"], "answer": "st.radio()"},
    {"question": "How do you clear cached data in Streamlit?", "options": ["st.cache_clear()", "st.clear_cache()", "st.rerun()", "None"], "answer": "st.cache_clear()"},
    {"question": "What does `st.metric()` do?", "options": ["Displays a KPI", "Creates a table", "Shows charts", "None"], "answer": "Displays a KPI"},
    {"question": "What is the default data input in `st.file_uploader()`?", "options": ["Binary", "String", "JSON", "None"], "answer": "Binary"},
    {"question": "Which Streamlit component handles form submissions?", "options": ["st.form()", "st.submit()", "st.form_submit()", "st.handle_form()"], "answer": "st.form()"},
],
    "Selenium": [
    {"question": "Which method is used to find an element by its ID in Selenium?", "options": ["find_element_by_id", "find_by_id", "get_element_by_id", "search_element_by_id"], "answer": "find_element_by_id"},
    {"question": "Which of these is not a Selenium-supported browser?", "options": ["Chrome", "Firefox", "Safari", "Opera"], "answer": "Opera"},
    {"question": "What does Selenium WebDriver do?", "options": ["Automates browsers", "Tests APIs", "Creates frameworks", "None"], "answer": "Automates browsers"},
    {"question": "Which function clicks on a web element in Selenium?", "options": ["click()", "press()", "activate()", "trigger_click()"], "answer": "click()"},
    {"question": "Which language is not supported by Selenium WebDriver?", "options": ["Java", "Python", "JavaScript", "Ruby"], "answer": "JavaScript"},
    {"question": "How do you maximize a browser window in Selenium?", "options": ["driver.maximize_window()", "driver.window_maximize()", "driver.set_fullscreen()", "driver.fullscreen()"], "answer": "driver.maximize_window()"},
    {"question": "Which method finds an element by name?", "options": ["find_element_by_name", "find_by_name", "get_element_by_name", "search_element_by_name"], "answer": "find_element_by_name"},
    {"question": "What does the `implicitly_wait` method do?", "options": ["Waits for elements to load", "Closes the browser", "Clears the cache", "Pauses the script"], "answer": "Waits for elements to load"},
    {"question": "How do you switch to a different tab in Selenium?", "options": ["driver.switch_to.window()", "driver.change_tab()", "driver.switch_tab()", "driver.change_window()"], "answer": "driver.switch_to.window()"},
    {"question": "Which method captures a screenshot in Selenium?", "options": ["driver.save_screenshot()", "driver.capture()", "driver.take_screenshot()", "driver.get_screenshot()"], "answer": "driver.save_screenshot()"},
    {"question": "What does the `quit()` method do in Selenium?", "options": ["Closes all browser windows", "Closes the current window", "Logs out of the session", "Pauses the driver"], "answer": "Closes all browser windows"},
    {"question": "What does the `get()` method do in Selenium?", "options": ["Opens a URL", "Gets the page title", "Retrieves cookies", "Fetches element properties"], "answer": "Opens a URL"},
    {"question": "Which method is used to find elements by XPath?", "options": ["find_element_by_xpath", "find_xpath", "get_element_by_xpath", "search_by_xpath"], "answer": "find_element_by_xpath"},
    {"question": "What is the purpose of the `ActionChains` class?", "options": ["Perform advanced user interactions", "Run JavaScript", "Clear cookies", "Manage browser logs"], "answer": "Perform advanced user interactions"},
    {"question": "How do you scroll to an element in Selenium?", "options": ["execute_script()", "scroll_into_view()", "scroll_to()", "driver.scroll()"], "answer": "execute_script()"},
    {"question": "Which method is used to close the current browser window?", "options": ["driver.close()", "driver.quit()", "driver.stop()", "driver.end()"], "answer": "driver.close()"},
    {"question": "What is the WebDriverWait used for?", "options": ["Explicitly wait for conditions", "Log browser actions", "Debug scripts", "None"], "answer": "Explicitly wait for conditions"},
    {"question": "Which method retrieves the page title?", "options": ["driver.title", "driver.get_title()", "driver.page_title()", "driver.fetch_title()"], "answer": "driver.title"},
    {"question": "What is the purpose of `switch_to.frame()`?", "options": ["Switch to an iframe", "Switch tabs", "Switch windows", "Switch modes"], "answer": "Switch to an iframe"},
    {"question": "Which type of testing is Selenium mainly used for?", "options": ["UI testing", "API testing", "Database testing", "Unit testing"], "answer": "UI testing"},
    {"question": "Which module handles options like headless mode?", "options": ["webdriver.Options", "webdriver.ChromeOptions", "webdriver.Config", "webdriver.Parameters"], "answer": "webdriver.ChromeOptions"},
    {"question": "How do you handle JavaScript alerts in Selenium?", "options": ["switch_to.alert()", "alert.handle()", "driver.alert()", "None"], "answer": "switch_to.alert()"},
    {"question": "Which method is used to find multiple elements by tag name?", "options": ["find_elements_by_tag_name", "find_by_tags", "get_all_elements()", "find_all_by_tag()"], "answer": "find_elements_by_tag_name"},
    {"question": "What does the `send_keys()` method do?", "options": ["Enters text into an input field", "Submits a form", "Clears text", "Highlights an element"], "answer": "Enters text into an input field"},
    {"question": "How do you delete all cookies in Selenium?", "options": ["driver.delete_all_cookies()", "driver.clear_cookies()", "driver.remove_cookies()", "driver.clean_cookies()"], "answer": "driver.delete_all_cookies()"},
    {"question": "Which locator strategy is the fastest in Selenium?", "options": ["ID", "Class Name", "XPath", "CSS Selector"], "answer": "ID"},
    {"question": "What does `is_displayed()` check for?", "options": ["Visibility of an element", "Accessibility of an element", "Enabled status of an element", "None"], "answer": "Visibility of an element"},
    {"question": "Which Selenium method waits for an alert to appear?", "options": ["wait.until(alert_is_present())", "driver.wait_for_alert()", "driver.alert_wait()", "None"], "answer": "wait.until(alert_is_present())"},
    {"question": "How do you retrieve cookies in Selenium?", "options": ["driver.get_cookies()", "driver.cookies()", "driver.fetch_cookies()", "driver.retrieve_cookies()"], "answer": "driver.get_cookies()"},
    {"question": "What is the default timeout for implicit wait?", "options": ["0 seconds", "10 seconds", "30 seconds", "60 seconds"], "answer": "0 seconds"},
    {"question": "Which type of locator is most flexible in Selenium?", "options": ["XPath", "CSS Selector", "Tag Name", "ID"], "answer": "XPath"},
    {"question": "What does `stale_element_reference_exception` indicate?", "options": ["Element is no longer valid", "Locator not found", "Driver timeout", "Invalid script"], "answer": "Element is no longer valid"},
    {"question": "Which Python package provides bindings for Selenium?", "options": ["selenium", "selenium-python", "webdriver", "selenium-tools"], "answer": "selenium"},
    {"question": "What is the purpose of `execute_script()` in Selenium?", "options": ["Run JavaScript in the browser", "Trigger events", "Start WebDriver", "Clear cache"], "answer": "Run JavaScript in the browser"},
    {"question": "Which command installs Selenium in Python?", "options": ["pip install selenium", "conda install selenium", "install selenium", "python -m selenium"], "answer": "pip install selenium"},
    {"question": "How do you get the current URL in Selenium?", "options": ["driver.current_url", "driver.url", "driver.get_url()", "driver.page_url"], "answer": "driver.current_url"},
    {"question": "How do you pause execution for a set time?", "options": ["time.sleep()", "wait()", "pause_execution()", "None"], "answer": "time.sleep()"},
    {"question": "What is the purpose of the `add_argument('--headless')` option?", "options": ["Run the browser in headless mode", "Add debugging info", "Enable logging", "None"], "answer": "Run the browser in headless mode"},
    {"question": "What does `find_elements` return?", "options": ["A list of elements", "A single element", "An element's attribute", "None"], "answer": "A list of elements"},
    {"question": "Which exception is raised when an element is not found?", "options": ["NoSuchElementException", "TimeoutException", "ElementNotVisibleException", "None"], "answer": "NoSuchElementException"},
    {"question": "How do you refresh the page in Selenium?", "options": ["driver.refresh()", "driver.reload()", "driver.navigate()", "None"], "answer": "driver.refresh()"},
    {"question": "What does `clear()` do in Selenium?", "options": ["Clears text from input fields", "Deletes cookies", "Stops the driver", "None"], "answer": "Clears text from input fields"},
    {"question": "What does `alert.dismiss()` do?", "options": ["Closes an alert", "Accepts an alert", "Creates an alert", "None"], "answer": "Closes an alert"},
    {"question": "How do you close only the current browser tab?", "options": ["driver.close()", "driver.quit()", "driver.end_tab()", "None"], "answer": "driver.close()"},
],
}

# Dropdown menu to select a quiz topic
selected_topic = st.selectbox("Select a quiz topic:", list(quiz_data.keys()))

if selected_topic:
    st.subheader(f"{selected_topic} Quiz")
    questions = quiz_data[selected_topic]

    # Track user answers
    user_answers = {}
    for index, q in enumerate(questions):
        st.write(f"**Question {index + 1}: {q['question']}**")
        user_answers[index] = st.radio(f"Choose the correct answer for Question {index + 1}:", q["options"], key=f"q{index}")
    
    # Submit button for the entire quiz
    if st.button("Submit Quiz"):
        # Calculate the score
        correct_answers = 0
        detailed_results = []

        for index, q in enumerate(questions):
            if user_answers[index] == q["answer"]:
                correct_answers += 1
                detailed_results.append((index + 1, q['question'], user_answers[index], "Correct", None))
            else:
                detailed_results.append((index + 1, q['question'], user_answers[index], "Incorrect", q['answer']))
        
        # Display the results
        st.success(f"Quiz Completed! 🎉 You scored {correct_answers} out of {len(questions)}.")
        st.write("### Detailed Results:")

        for result in detailed_results:
            q_num, question, user_answer, status, correct_answer = result
            if status == "Correct":
                st.write(f"✅ **Question {q_num}: {question}** - Your Answer: `{user_answer}` - {status}")
            else:
                st.write(f"❌ **Question {q_num}: {question}** - Your Answer: `{user_answer}` - {status}")
                st.write(f"   Correct Answer: `{correct_answer}`")

